server {
    listen 8081;
    listen [::]:8081;

    server_name <SERVER_NAME>;

    root /src/index.html;
    index index.html;

    access_log /var/log/nginx/huynq-k24cntt2.access.log;
    error_log /var/log/nginx/huynq-k24cntt2.error.log;

    location / {

        try_files $uri $uri/ =404;
    }
}
